CREATE TABLE IF NOT EXISTS cashier_settings (
    id SERIAL PRIMARY KEY,
    store_name VARCHAR(255) DEFAULT 'ERP Mart Store',
    store_address TEXT DEFAULT '123 Commerce Way, Tech City',
    phone VARCHAR(50) DEFAULT '+1 (555) 019-2831',
    email VARCHAR(150) DEFAULT 'support@erpmart.com',
    receipt_footer TEXT DEFAULT 'Thank you for shopping with us! Please come again.',
    show_logo BOOLEAN NOT NULL DEFAULT TRUE,
    show_tax BOOLEAN NOT NULL DEFAULT TRUE,
    show_cashier_name BOOLEAN NOT NULL DEFAULT TRUE,
    show_customer_name BOOLEAN NOT NULL DEFAULT TRUE,
    auto_print_receipt BOOLEAN NOT NULL DEFAULT FALSE,
    default_tax_percentage NUMERIC(5,2) NOT NULL DEFAULT 5.00,
    allow_negative_stock BOOLEAN NOT NULL DEFAULT FALSE,
    require_customer BOOLEAN NOT NULL DEFAULT FALSE,
    allow_discount BOOLEAN NOT NULL DEFAULT TRUE,
    maximum_discount_percentage NUMERIC(5,2) NOT NULL DEFAULT 50.00,
    auto_clear_cart BOOLEAN NOT NULL DEFAULT TRUE,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
